### ISSUE TITLE
Suggestion/Proposal

### ISSUE THREAD

**Issue by sridharrajaram** [github-profile-achievements/english#25]
Hi Team,

I would like to propose the introduction of new badges on GitHub to encourage consistent engagement from users, especially beginners. These badges could celebrate milestones such as the longest 50-day streak, longest 100-day streak, longest 500-day streak, and longest 1000-day streak. I believe that implementing these badges could be particularly beneficial for individuals who are new to programming and are motivated to maintain their commitment to using GitHub regularly.

This idea came to mind when I noticed a significant number of people on LinkedIn participating in the 100-day code challenge. By incorporating such streak-related badges on GitHub, we could tap into this trend and provide additional incentives for users to remain active on the platform.

**Comment by gomzyakov** [comment]
@sridharrajaram Hello!

I'm sorry, but this is not a repository through which you can contact the developers of GitHub and offer your ideas :(

Try writing to this community https://github.com/community
