### ISSUE TITLE
Your tip not working 

### ISSUE THREAD

**Issue by deepbajud** [github-profile-achievements/english#26]

**Comment by gomzyakov** [comment]
@deepbajud Hello!

What advice are you talking about?

**Comment by deepbajud** [comment]
You give a process of how to earn Highlight badge in this badge "✓" - Discussion answered  - Have your reply to a discussion marked as the answer. check my profile I also gives many right answer in discussion but till I don't earn any badge

**Comment by deepbajud** [comment]
Thanks @gomzyakov your all information very useful for me Except Discussion Answered but also thank for changes details of that badge

**Comment by deepbajud** [comment]
can you merge my pull request for making my profile strong and your project perfect.

**Comment by 20481A05K0** [comment]
@gomzyakov hey there This is Prasoon Kumar reacted with heart symbol getting a badge is not working now. Check once yaar
