### ISSUE TITLE
Grammar/typo bug

### ISSUE THREAD

**Issue by carlycue** [github-profile-achievements/english#33]
![image](https://github.com/github-profile-achievements/english/assets/23388930/f56c5f55-5728-4d04-b85b-b00859100302)

Super minor, but should probably read `Coauthored in two or more merged pull requests.`

**Comment by carlycue** [comment]
Alternatively: `Coauthored a commit in two or more merged pull requests.`

**Comment by gomzyakov** [comment]
@carlycue Hello!

Thank you for your comment! Can you fix this?)
