### ISSUE TITLE
Update suggestion for the Galaxy Brain achievement description.

### ISSUE THREAD

**Issue by davevad93** [github-profile-achievements/english#48]
Hi, I have a suggestion regarding the description of the `Galaxy Brain` achievement. Recently, GitHub staff has disabled the achievements via [Community discussions](https://github.com/orgs/community/discussions/) , so I think it should be pointed out in the description.

Source:
- [Achievements will no longer be available in the Community](https://github.com/orgs/community/discussions/106536)

**Comment by As90909w** [comment]
ok

**Comment by gomzyakov** [comment]
@davevad93 @As90909w 

Can you make a PR with edits?

**Comment by davevad93** [comment]
@gomzyakov 
Of course, thank you!

**Comment by davevad93** [comment]
Hi @gomzyakov ,

I've opened the `pull request` with the edits.

**Comment by gomzyakov** [comment]
@davevad93 

PR https://github.com/github-profile-achievements/english/pull/49 is merged!

Thanks for your contribution!
