### ISSUE TITLE
Achievement Badges 

### ISSUE THREAD

**Issue by Himanshu12866** [github-profile-achievements/english#56]
![Screenshot 2024-07-04 133850](https://github.com/github-profile-achievements/english/assets/130586038/60131c0b-e50f-42c2-8c55-c8ae612684d4)
In my profile , achievements badges are not showing . All required settings are enabled but still it is not working . I tried a lot to fix it but got same result.

Please give me solution to fix it

**Comment by jaycee0610** [comment]
❤️

**Comment by gomzyakov** [comment]
@Himanshu12866 Hello!

<img width="711" alt="image" src="https://github.com/github-profile-achievements/english/assets/1460709/5dd78975-c30f-4e7a-94b8-6c77360076ca">

Is the checkbox enabled? Did you press this button?

**Comment by Himanshu12866** [comment]
Yes

**Comment by Himanshu12866** [comment]
![Screenshot 2024-07-05 132447](https://github.com/github-profile-achievements/english/assets/130586038/fce44615-8a3e-4d16-9a3a-f5cd91258501)

**Comment by gomzyakov** [comment]
@Himanshu12866 

In this case, unfortunately, I cannot help. I recommend contacting official Github support https://support.github.com

**Comment by Himanshu12866** [comment]
OK I'll try to contact 
Thank You

**Comment by gomzyakov** [comment]
@Himanshu12866 

Can I close this issue?

**Comment by Himanshu12866** [comment]
Did not get the answer 😢
