### ISSUE TITLE
Hubber Champion Badge

### ISSUE THREAD

**Issue by demiwright** [github-profile-achievements/english#59]
Hi, I was wondering if it is possible to create a Hubber Champion badge for our new FY25 Hubber Champions? https://github.com/github/Hubber-Champions/blob/master/README.md

Thank you!
Demi

**Comment by spageektti** [comment]
Hi. I'm not a maintainer of this repo or something, but AFAIK this repo is just a list of achievements created by **GitHub**, so this is not the right place for such requests if the badge doesn't exist yet. Also, the link you provided returns 404, so either the link is invalid or the repository is private.

**Comment by demiwright** [comment]
thank you @spageektti
